name: jonahbsanders
favicon: null
layout_spectrum: 0.6269648356828839
typography_spectrum: 0.5115046475548297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6291800925973803
  lightness: 0.8865279611200094
  saturation: 0.5624261817429215
  rhythmicContrast: 0.41556363622657955
purpose: []
