analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.6269648356828839
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5624261817429215
  brandStrength: 0.6291800925973803
  rhythmicContrast: 0.4155636362265795
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.8865279611200094
purpose: []
favicon: null
name: jonahbsanders
typography_spectrum: 0.5115046475548297
